events {}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;
    absolute_redirect off;
    
    add_header X-Debug-Proxy "nginx" always;

    location = / {
      return 302 /app/;
    }

    location /app/ {
      rewrite ^/app/(.*)$ /$1 break;

      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://web:8000;
    }

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;

      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://api:5000;
    }
  }
}