@startuml
skinparam backgroundColor white
skinparam shadowing false
skinparam roundcorner 12
skinparam defaultFontName Arial
skinparam defaultFontSize 14

participant Client
participant Server

Client -> Server : ClientHello\n(key share)
Server -> Client : ServerHello\nEncrypted Extensions\nCertificate\nFinished
Client -> Server : Finished

Client -> Server : Application Data
Server -> Client : Application Data

@enduml
